/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    InputNode: typeof import('./components/InputNode.vue')['default']
    LeftNav: typeof import('./components/LeftNav.vue')['default']
    LLMNode: typeof import('./components/LLMNode.vue')['default']
    OutputNode: typeof import('./components/OutputNode.vue')['default']
    ResultNode: typeof import('./components/ResultNode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpecialEdge: typeof import('./components/SpecialEdge.vue')['default']
    SpecialNode: typeof import('./components/SpecialNode.vue')['default']
    TopNav: typeof import('./components/TopNav.vue')['default']
  }
}
